import {
  Darker_Grotesque,
  Nunito_Sans,
  Red_Hat_Display,
} from "next/font/google";
import "@/styles/global.css";

const darker_grotesque = Darker_Grotesque({
  subsets: ["latin"],
  weight: ["700"],
  variable: "--font-darker-grotesque",
});

const nunito_sans = Nunito_Sans({
  subsets: ["latin"],
  weight: ["400", "700", "800"],
  variable: "--font-nunito-sans",
  display: "swap",
});

const red_hat_display = Red_Hat_Display({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-red-hat-display",
});

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${darker_grotesque.variable} ${nunito_sans.variable} ${red_hat_display.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
